nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: BileMoAPI
            description: This is an awesome API REST for BileMo!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!(/doc|/doc.json)$)
        #host_patterns:
        #    - ^/api
    
    
    
