controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api
    name_prefix: api_
    requirements:
        locale: en

kernel:
    resource: ../../src/Kernel.php
    type: annotation
